# Generated by Django 5.1.2 on 2024-11-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('search_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-search_time'],
            },
        ),
    ]
